//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studentOrg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volunteer
    {
        public int id { get; set; }
        public string Name { get; set; }
        public System.DateTime joinDate { get; set; }
        public string Marital_status { get; set; }
        public string sex { get; set; }
        public int age { get; set; }
        public int Identification_Number { get; set; }
        public string address { get; set; }
        public Nullable<int> mobile { get; set; }
        public string educational_attainment { get; set; }
        public string university_or_school { get; set; }
        public Nullable<int> programId { get; set; }
        public Nullable<float> owed_money { get; set; }
        public Nullable<int> Evaluation { get; set; }
    
        public virtual Programe Programe { get; set; }
    }
}
